### PR TITLE
Fixed some inconsistencies

### PR DESCRIPTION
**Pull request by ThatFrogDev**
## Changelog
- Custom scrollbar and links for the license
- Changed the names of page2 and page3
- The next button only appears if you select something at the toolselector
- When you disagree the license agreement the app won't close but you're taken back to the splash screen (it seemed a bit abrupt to me to close the app directly, but this is just a temporary solution. In my opinion the best way is to either remove the disagree button or make a popup)
- Some small tweaks

## Problems I encountered but didn't fix
These are some problems that are probably known but are things for future pull requests
- There is probably some useless CSS (example: toolselector.css, as far as I know you can use multiple stylesheets for one page)
- There is probably some useless/buggy code (I didn't read all of the code, so I'm not sure)
- The minimize and plus button are a bit weirdly spaced (I think it's an SVG issue)
- When you minimize it's really abrupt (on Windows it's not like the normal minimize function)

Also I think it's cool to add images to the tools (toolselector page)

### CODE REVIEW

**Comment by SunightMC** [comment]
LGTM!!! 

PS: the minimizing thing is weird because I didn't implement it properly

**Review by SunightMC — APPROVED** [review]

**Comment by ThatFrogDev** [comment]
> LGTM!!!
> 
> PS: the minimizing thing is weird because I didn't implement it properly

Nice! Okay, we need to implement it properly then. I will add it to my list of possible changes 👍

**Comment by ThatFrogDev** [comment]
Bruh i already added it lol

**Comment by SunightMC** [comment]
> > LGTM!!!
> > PS: the minimizing thing is weird because I didn't implement it properly
> 
> Nice! Okay, we need to implement it properly then. I will add it to my list of possible changes 👍

I don’t even know how you got minimising to work, as it doesn’t work for me 😂

**Pull request merged**
