### PR TITLE
Updated electron + made the window transparent

### PR DESCRIPTION
**Pull request by SunightMC**
Bumped the electron version from v19 to v22 and remade the window to be transparent as many people suggested.

### CODE REVIEW

**Comment by ThatFrogDev** [comment]
LGTM!

(oh shit 😞i can't merge)

**Comment by MrSerge01** [comment]
> LGTM!
> 
> (oh shit 😞i can't merge)

lol

**Comment by MrSerge01** [comment]
@SunightMC bro ur check failed

**Comment by SunightMC** [comment]
> @SunightMC bro ur check failed

I didn't implement the pipeline yet

**Review by Froxcey — APPROVED** [review]
Don't see any problem, LGTM! Merge when you feel ready.

vibe

**Pull request merged**
